version: 2
jobs: 
  build:
    working_directory: ~/app
    docker:
      - image: circleci/clojure:tools-deps-1.10.1.502
    steps:
      - checkout 
      - run: clojure -A:runner:test














